/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IConvexHandler,
  IConvexHandlerInterface,
} from "../IConvexHandler";

const _abi = [
  {
    inputs: [],
    name: "baseRewardPool",
    outputs: [
      {
        internalType: "contract IConvexRewards",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ust3Pool",
    outputs: [
      {
        internalType: "contract ICurvePool",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IConvexHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IConvexHandlerInterface {
    return new utils.Interface(_abi) as IConvexHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConvexHandler {
    return new Contract(address, _abi, signerOrProvider) as IConvexHandler;
  }
}
